@echo off

mkdir C:\REDE


mkdir C:\REDE\ALAN-SOARES
mkdir C:\REDE\ANDREA-SANTOS
mkdir C:\REDE\BRUNO-OLIVEIRA
mkdir C:\REDE\CAMILA-LIRA
mkdir C:\REDE\CARLOS-SOUSA
mkdir C:\REDE\CAROLINE-NASCIMENTO
mkdir C:\REDE\DANIEL-SANTANA
mkdir C:\REDE\DARIO-FARIAS
mkdir C:\REDE\EDUARDO-RIOS
mkdir C:\REDE\FABIO-SILVA
mkdir C:\REDE\FELIPE-MACHADO
mkdir C:\REDE\FELIPE-BARRIOS
mkdir C:\REDE\FLAVIO-SOUZA
mkdir C:\REDE\FRANCISCO-CAVALCANTE
mkdir C:\REDE\GABRIEL-CREPALDI
mkdir C:\REDE\GABRIEL-LIMA
mkdir C:\REDE\GABRIEL-RODRIGUES
mkdir C:\REDE\GABRIELY-SILVA
mkdir C:\REDE\GUILHERME-ALVES
mkdir C:\REDE\GUSTAVO-TAVARES
mkdir C:\REDE\HENRIQUE-CABRAL
mkdir C:\REDE\ISAAC-SOUZA
mkdir C:\REDE\ISABELLY-MESQUITA
mkdir C:\REDE\JOAO-SOARES
mkdir C:\REDE\JONATHAN-FREITAS
mkdir C:\REDE\KAUA-MOTA
mkdir C:\REDE\LUCAS-SANTOS
mkdir C:\REDE\LUCAS-ANDRADE
mkdir C:\REDE\MATHEUS-CARVALHO
mkdir C:\REDE\NATALIA-MOREIRA
mkdir C:\REDE\NICOLAS-NASCIMENTO
mkdir C:\REDE\PALLOMA-SANTOS
mkdir C:\REDE\RAISSA-CARMO
mkdir C:\REDE\RAPHAELA-MELO
mkdir C:\REDE\REBECCA-GUEDES
mkdir C:\REDE\RIAM-ANDRE
mkdir C:\REDE\ROGERIO-JUNIOR
mkdir C:\REDE\SABRINA-BENEVIDES
mkdir C:\REDE\WALDANIA-OLIVEIRA

echo.
echo "Pastas criadas:"
dir C:\REDE /b
pause
